import assert from "node:assert/strict";
import test from "node:test";
import {mkdtemp,writeFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {bootstrapMachineState} from "../src/repository-machine/surfaces.mjs";
import {proposeTransition,executeTransition} from "../src/repository-machine/transition.mjs";
import {createActuationRequest} from "../contracts/actuation.mjs";
import {evaluateActuatorAdmission,executeActuation} from "../src/causal/actuation.mjs";
import {createGitCliAdapter} from "../src/repository-actuator/git-cli.mjs";
const exec=promisify(execFile); async function git(cwd,...args){return exec("git",args,{cwd});}
async function fixture(){const cwd=await mkdtemp(tmpdir()+"/ourself-v06-");await git(cwd,"init","-q");await git(cwd,"config","user.email","ourself@example.invalid");await git(cwd,"config","user.name","OURSELF v0.6 test");await writeFile(cwd+"/state.txt","C1\n");await git(cwd,"add","state.txt");await git(cwd,"commit","-q","-m","C1");const c1=(await git(cwd,"rev-parse","HEAD")).stdout.trim();await writeFile(cwd+"/state.txt","C2\n");await git(cwd,"add","state.txt");await git(cwd,"commit","-q","-m","C2");const c2=(await git(cwd,"rev-parse","HEAD")).stdout.trim();await git(cwd,"branch","cpu",c1);return{cwd,c1,c2};}
function transition(machine,c1,c2){const proposal=proposeTransition({machine,from:"input",to:"cpu",operation:"UPDATE_REF",authorized:true,bounded:true,metadata:{messageId:"MSG-V06"}});return executeTransition({machine,proposal,targetCommit:c2,causalBinding:{messageId:"MSG-V06",proposalId:"proposal_x",admissionId:"admission_x",instanceId:"instance_x",executionId:"execution_x",evidenceHash:"e".repeat(64),processorReceiptId:"receipt_x",processorFinalReceiptHash:"f".repeat(64)}});}
test("v0.6 rejects mismatched lineage receipt",async()=>{const f=await fixture();try{const m=bootstrapMachineState(f.c1),t=transition(m,f.c1,f.c2);const q=createActuationRequest({transitionReceipt:t.receipt,targetSurface:"cpu",expectedPreRef:"refs/heads/cpu",expectedPreCommit:f.c1,requestedPostCommit:f.c2});const a=evaluateActuatorAdmission({request:{...q,transitionReceiptHash:"0".repeat(64)},machine:m,transition:t,authorized:true,bounded:true});assert.equal(a.status,"REJECTED");assert.equal(a.reason,"TRANSITION_RECEIPT_MISMATCH");}finally{await rm(f.cwd,{recursive:true,force:true});}});
test("v0.6 reaches actual Git ref only after actuator success",async()=>{const f=await fixture();try{const m=bootstrapMachineState(f.c1),t=transition(m,f.c1,f.c2),q=createActuationRequest({transitionReceipt:t.receipt,targetSurface:"cpu",expectedPreRef:"refs/heads/cpu",expectedPreCommit:f.c1,requestedPostCommit:f.c2}),a=evaluateActuatorAdmission({request:q,machine:m,transition:t,authorized:true,bounded:true}),r=await executeActuation({actuatorAdmission:a,adapter:createGitCliAdapter({cwd:f.cwd})});assert.equal(a.status,"ACTUATOR_ADMITTED");assert.equal(r.status,"ACTUATOR_EXECUTED");assert.equal(r.actualState.commit,f.c2);assert.equal((await git(f.cwd,"rev-parse","refs/heads/cpu")).stdout.trim(),f.c2);assert.match(r.receipt.receiptHash,/^[0-9a-f]{64}$/);}finally{await rm(f.cwd,{recursive:true,force:true});}});
test("v0.6 failed actuator yields no actual state",async()=>{const f=await fixture();try{const m=bootstrapMachineState(f.c1),t=transition(m,f.c1,f.c2),q=createActuationRequest({transitionReceipt:t.receipt,targetSurface:"cpu",expectedPreRef:"refs/heads/cpu",expectedPreCommit:f.c1,requestedPostCommit:f.c2}),a=evaluateActuatorAdmission({request:q,machine:m,transition:t,authorized:true,bounded:true}),r=await executeActuation({actuatorAdmission:a,adapter:{async readRef(ref){return{ref,commit:f.c1}},async updateRef(){return{acknowledged:true}}}});assert.equal(r.status,"ACTUATOR_FAILED");assert.equal(r.actualState,null);}finally{await rm(f.cwd,{recursive:true,force:true});}});
