export const TRAP_CODES = Object.freeze({
  FETCH_BOUNDS:"FETCH_BOUNDS",
  REGISTER_BOUNDS:"REGISTER_BOUNDS",
  MEMORY_BOUNDS:"MEMORY_BOUNDS",
  PROGRAM_BOUNDS:"PROGRAM_BOUNDS",
  EXECUTION_BOUND:"EXECUTION_BOUND",
  INVALID_OPCODE:"INVALID_OPCODE",
});
