name: OURPROCESSORSELF CI Smoke

on:
  push:
    branches:
      - "mutation/**"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Prove runner
        run: echo "OURPROCESSORSELF GITHUB RUNNER ONLINE"
